version: '3'

services:

  # ==========================
  # NATS Server
  # ==========================
  nats-server:
    image: nats:latest

  # ==========================
  # Client Gateway
  # ==========================
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # ==========================
  # Auth Microservice
  # ==========================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  # # ==========================
  # # Products MS
  # # ==========================
  product-ms:
    build:
      context: ./product-ms
      dockerfile: dockerfile.prod
    image: product-ms-prod
    environment:
      - PORT=${PRODUCT_MS_PORT}
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  # ==========================
  # Orders MS
  # ==========================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=${ORDERS_MS_PORT}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  # # ==========================
  # # Payments Microservice
  # # ==========================
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${PAYMENTS_MS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}
      - NATS_SERVERS=nats://nats-server:4222
