apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/tienda-microservicios-464423/image-registry/payments-ms
        name: payments-ms
        env: 
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: stripe_secret
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:31871/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:31871/payments/cancel"
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secret
              key: stripe_endpoint_secret
        resources: {}
status: {}
